### ISSUE TITLE
Retrait des '/' sur la référence de transaction

### ISSUE THREAD

**Issue by PBarraco** [Horanet/payment_tipiregie#4]
Les caractères `/` retournés par la fonction `_tipiregie_form_get_tx_from_data` sont pas remplacés par des espaces. Il faudrait les laisser.

**Comment by MTantin** [comment]
Le service web de Tipi Régie n'accepte aucun des caractères spéciaux. J'ai donc remplacé les '/' par des '  slash  ' afin de les différencier et pouvoir les re-transformer en '/' au retour du paiement.
Commit 90855167031cf244ff0d4ca8ebaee1009cbbacb5
